#logging:
#  config: classpath:logback-spring.xml
spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: "jdbc:sqlserver://10.10.140.50:1433;database=ERP"
    username: sap
    password: nelcfen@I*XDO0xP
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    cache-enabled: false