#logging:
#  config: classpath:logback-spring-mac.xml
spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: "jdbc:sqlserver://10.10.144.52:1433;database=ERP"
    username: sap
    password: mjgytoeMGfzOaTN2
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    cache-enabled: false

#configuration:
#  log-impl: org.apache.ibatis.logging.stdout.StdOutImpl