logging:
  config: classpath:logback.xml
spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: "jdbc:sqlserver://56.56.59.16:1433;database=ERP"
    username: sap
    password: 1234
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    cache-enabled: false