logging:
  config: classpath:logback.xml
spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: "jdbc:sqlserver://56.56.56.16:1433;database=ERP"
    username: sap
    password: 1234